### ISSUE TITLE
Set up semantic release of packages to npm

### ISSUE THREAD

**Issue by JohanObrink** [seb-neo/sebspark#1]
Auto publish on successful lint/test/build etc

**Comment by believer** [comment]
Maybe [changesets](https://github.com/changesets/changesets) could be something to look at? It's focused on creating releases from monorepo repositories.

**Comment by JohanObrink** [comment]
@believer Sure! Have never used it but I also never saw a good setup for working with releases in a package based monorepo so let's do it 😄

**Comment by believer** [comment]
@JohanObrink I'll see what I can do! Do we need an organization on `npm` for it? Should they be published as private packages?

**Comment by JohanObrink** [comment]
@believer 

![Image](https://github.com/seb-neo/sebspark/assets/548783/189b5c71-017b-4d60-aa5d-3cac7da62138)

**Comment by believer** [comment]
This process with [Changesets](https://github.com/changesets/changesets) is semi-automatic.

- You create "changesets" locally using `yarn changeset`. It opens a guide where you specify which package to update and what the change is. This gives us control of when a new release should be created as all changes, like minor updates or documentation changes, probably don't require a release.
- Once the change is pushed, a [release PR](https://github.com/seb-neo/sebspark/pull/3) is created using a GitHub action when unprocessed changesets exist in the repository. The PR is created only if [lint and tests pass](https://github.com/seb-neo/sebspark/actions/runs/5218811954). If a PR already exists, it is updated with the new changes.
- Upon merging the PR, the changesets are consumed.


Next up, I'll add automatic publishing to `npm` when the PR is merged.

**Comment by JohanObrink** [comment]
@believer How do you specify which package is changed?

**Comment by believer** [comment]
@JohanObrink it shows a wizard where you can select one or more packages that should be updated. Here's an example screenshot:
![Screenshot 2023-06-09 at 08 50 06](https://github.com/seb-neo/sebspark/assets/1478102/22d3358c-a948-4bd1-8024-598f5dff0dce)

**Comment by JohanObrink** [comment]
![Nice](https://media.tenor.com/KMxrZ-A6ev4AAAAC/nice-smack.gif)
